apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: example
    #  namespace: foo
spec:
  rules:
    - host: www.example.com
      http:
        paths:
          - backend:
              serviceName: exampleService
              servicePort: 4200
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  #    tls:
  #        - hosts:
  #            - www.example.com
  #          secretName: example-tls
